global:
  scrape_interval: 1s
  evaluation_interval: 1s

rule_files:
 - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-west-2
        access_key: ${AWS_READ_EC2_ACCESS_KEY}
        secret_key: ${AWS_READ_EC2_ACCESS_SECRET}
        port: 9100
