- name: "Unzip artifact"
  become: true
  unarchive:
    src: /home/circleci/project/artifact.tar.gz
    dest: ~/backend

- name: Give insecure permissions to an existing file
  file:
    path: ~/backend
    owner: ubuntu
    group: ubuntu
    mode: '1777'

- name: "Start backend"
  become: true
  shell: |
    cd ~/backend
    npm install
    pm2 stop default
    pm2 start npm -- start