- name: ensure backend directory exists
  file:
    path: /root/backend
    state: directory

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/unarchive_module.html
- name: "Unzip artifact"
  become: true
  unarchive:
    src: /home/circleci/project/artifact.tar.gz
    dest: /root/backend

- name: Give insecure permissions to an existing file
  file:
    path: /root/backend
    owner: ubuntu
    group: ubuntu
    mode: '1777'

- name: "Start backend"
  become: true
  shell: |
    cd /root/backend
    npm install
    pm2 stop default
    pm2 start npm -- start